name: Gradle Build and Test Dommern
description: 'Sets up JDK 21 and builds the project using Gradle'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      # Note: It is best practice to use the specific version or SHA for stability
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash
