name: Tailscale deploy Dommern
description: 'Connects the runner to a Tailscale network using OAuth credentials'
inputs:
  oauth-client-id:
    description: 'Tailscale OAuth Client ID'
    required: true
  oauth-secret:
    description: 'Tailscale OAuth Client Secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ inputs.oauth-client-id }}
        oauth-secret: ${{ inputs.oauth-secret }}