name: "Build and Push Docker Image to GHCR (Compose)"
description: "Build with docker-compose, tag with commit SHA and latest, push to GHCR"

inputs:
  service:
    description: "docker-compose service name"
    required: true

  local_image:
    description: "Local image name produced by docker-compose"
    required: true

  ghcr_image:
    description: "GHCR image name (without registry)"
    required: true


runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build image with docker-compose
      shell: bash
      run: |
        docker compose build

    - name: Tag image
      shell: bash
      run: |
        docker tag dommern:latest \
          ghcr.io/vejmon/dommern:${GITHUB_SHA}

        docker tag dommern:latest \
          ghcr.io/vejmon/dommern:latest

    - name: Push images
      shell: bash
      run: |
        docker push ghcr.io/vejmon/dommern --all-tags
