name: "Build and Push Docker Image to GHCR (Compose)"
description: "Build with docker-compose, tag with commit SHA and latest, push to GHCR"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push multi-platform image
      shell: bash
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/vejmon/dommern:${GITHUB_SHA} \
          -t ghcr.io/vejmon/dommern:latest \
          --push \
          .

